wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.7.17
    cli_version: 0.17.6
    framework: huggingface
    huggingface_version: 4.30.2
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1723478868
    t:
      1:
      - 1
      - 5
      - 9
      - 11
      - 41
      - 48
      - 49
      - 53
      - 55
      - 63
      - 80
      - 103
      2:
      - 1
      - 5
      - 9
      - 11
      - 41
      - 48
      - 49
      - 53
      - 55
      - 63
      - 80
      - 103
      3:
      - 7
      - 13
      - 23
      - 66
      4: 3.7.17
      5: 0.17.6
      6: 4.30.2
      8:
      - 5
      13: linux-x86_64
    m:
    - 1: trainer/global_step
      6:
      - 3
